name: fountain_fm
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.3

  # State Management
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^1.0.0-dev.11
  state_notifier: ^0.7.1
  google_fonts: ^2.1.0
  line_icons: ^2.0.1

  gap:
  dartz: ^0.10.0-nullsafety.1

  intl: ^0.17.0
  go_router: ^2.1.1
  logger: ^1.1.0
  page_transition: ^2.0.4
  salomon_bottom_bar: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.0
  very_good_analysis: ^2.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/png/
